apiVersion: v1
kind: Service
metadata:
  name: ossa-website
  namespace: default
  labels:
    app: ossa-website
spec:
  type: NodePort
  selector:
    app: ossa-website
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  sessionAffinity: None
