apiVersion: v1
kind: Service
metadata:
  name: {{ include "ossa.fullname" . }}
  labels:
    {{- include "ossa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ossa.service.type }}
  ports:
    - port: {{ .Values.ossa.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ossa.selectorLabels" . | nindent 4 }}