version: '3.8'

services:
  ossa:
    environment:
      - NODE_ENV=development
      - DEBUG=ossa:*
      - LOG_LEVEL=DEBUG
    volumes:
      - ../../src:/app/src
      - ../../package.json:/app/package.json
      - ../../tsconfig.json:/app/tsconfig.json
    command: npm run dev