# OSSA Grafana Datasource Configuration
# Version: 0.1.8 - Enterprise Monitoring Stack

apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: OSSA-Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: ossa-prometheus
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "30s"
      exemplarTraceIdDestinations:
        - datasourceUid: ossa-jaeger
          name: TraceID
      prometheusType: Prometheus
      prometheusVersion: "2.40.0"
    secureJsonData: {}

  - name: OSSA-Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    uid: ossa-jaeger
    url: http://jaeger:16686
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: ossa-loki
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false

  - name: OSSA-Loki
    type: loki
    access: proxy
    orgId: 1
    uid: ossa-loki
    url: http://loki:3100
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      maxLines: 1000
      derivedFields:
        - datasourceUid: ossa-jaeger
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: OSSA-VictoriaMetrics
    type: prometheus
    access: proxy
    orgId: 1
    uid: ossa-victoria
    url: http://victoria-metrics:8428
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "30s"
      prometheusType: Prometheus
      prometheusVersion: "2.40.0"
      customQueryParameters: "extra_label=datasource&extra_label=victoria"

  - name: OSSA-AlertManager
    type: alertmanager
    access: proxy
    orgId: 1
    uid: ossa-alertmanager
    url: http://alertmanager:9093
    version: 1
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false