{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-base.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.agent.id }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

